version: "1"

steps:
  - name: make_deps
    image: alpine:latest
    pull: true
    commands:
      - mkdir foo
      - echo "my deps" > foo/bar.txt

  - name: ls_1
    image: alpine:latest
    pull: true
    commands:
      - ls -la

  - name: rebuild_cache
    image: docker.target.com/vela-plugins/s3-cache:v0.3.0-1
    pull: true
    secrets: [ cache_s3_server, cache_s3_access_key, cache_s3_secret_key ]
    parameters:
      action: rebuild
      log_level: debug
      mount:
        - foo

  - name: rm -rf foo
    image: alpine:latest
    pull: true
    commands:
      - rm -rf foo

  - name: ls_2
    image: alpine:latest
    pull: true
    commands:
      - ls -la

  - name: restore_cache
    image: docker.target.com/vela-plugins/s3-cache:v0.3.0-1
    pull: true
    secrets: [ cache_s3_server, cache_s3_access_key, cache_s3_secret_key ]
    parameters:
      log_level: debug
      action: restore

  - name: ls_3
    image: alpine:latest
    pull: true
    commands:
      - ls -la

secrets:
  - name: cache_s3_server
    key:  vela/prod-secrets/cache_s3_server
    engine: native
    type: shared
  - name: cache_s3_access_key
    key:  vela/prod-secrets/cache_s3_access_key
    engine: native
    type: shared
  - name: cache_s3_secret_key
    key:  vela/prod-secrets/cache_s3_secret_key
    engine: native
    type: shared