# name of the action
name: prerelease

# trigger on push events with `v*` in tag
on:
  push:
    tags:
      - 'v*'

# pipeline to execute
jobs:
  prerelease:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
    - name: clone
      uses: actions/checkout@v2

    - name: build
      env:
        GOOS: linux
        CGO_ENABLED: '0'
      run: |
        go build -a \
          -ldflags '-s -w -extldflags "-static"' \
          -o release/vela-s3-cache \
          github.com/go-vela/vela-s3-cache/cmd/vela-s3-cache

    - name: publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: target/vela-s3-cache
        cache: true
        tag_names: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
